### ISSUE TITLE
Boilerplate planning

### ISSUE THREAD

**Issue by jjaderg** [jjaderg/jellbo#3]
Following is the list with the pending implementations for this boilerplate:

- [ ] Describe the use and installation
- [ ] Add architecture and style guide css
- [ ] Implement continuos integration -  `Travis` 
- [ ] Create a demo web page explaining the use
- [ ] Implement unit testing - `karma, chai, jasmine, whatever` :mag:
- [ ] Create a better logo, cute, cool :scream:

**Comment by mvfsilva** [comment]
Back to work?

**Comment by jjaderg** [comment]
Yep :thumbsup:
